class AppStrings {
  static const Map<String, Map<String, String>> _data = {
    'en': {
      'app_name': 'RythuMitra',
      'tagline': 'Best Net Realization — Not Just Highest Price',
      'select_language': 'Select Your Language',
      'language_subtitle': 'Choose the language you are comfortable with',
      'continue_btn': 'Continue',
      'welcome': 'Welcome',
      'farmer': 'Farmer',
      'find_best': 'Find Best Option',
      'find_best_sub': 'Calculate net profit after transport & risk',
      'buyer_network': 'Buyer Network',
      'buyer_network_sub': 'Connect with traders & processors',
      'post_demand': 'Post Demand',
      'post_demand_sub': 'List your harvest for buyers',
      'voice_assistant': 'Voice Assistant',
      'nearby_markets': 'Nearby Markets',
      'mandi_prices': 'Today\'s Mandi Prices',
      'recent_searches': 'Recent Searches',
      'your_crop': 'Your Crop',
      'select_crop': 'Select Crop',
      'quantity': 'Quantity',
      'quantity_sub': 'How many kilograms do you have?',
      'location': 'Your Location',
      'location_sub': 'Where is your farm?',
      'transport': 'Transportation',
      'transport_sub': 'How will you move the harvest?',
      'own_vehicle': 'Own Vehicle',
      'own_vehicle_sub': 'I have my own truck/vehicle',
      'rental_vehicle': 'Rental Vehicle',
      'rental_vehicle_sub': 'I will hire a vehicle',
      'no_vehicle': 'No Vehicle',
      'no_vehicle_sub': 'Need buyer pickup or market arrangement',
      'use_gps': 'Use My GPS Location',
      'detecting': 'Detecting location...',
      'gps_success': 'Location detected!',
      'gps_error': 'Could not detect GPS. Please select a town.',
      'search_btn': 'Find Best Market',
      'searching': 'Scanning markets...',
      'scanning_radius': 'Scanning {radius} km radius',
      'markets_found': '{count} markets found',
      'expanding': 'Expanding search radius...',
      'calculating': 'Calculating net realization...',
      'comparing': 'Comparing prices, transport & risk...',
      'best_option': 'Best Option',
      'net_realization': 'Net Realization',
      'you_earn_more': 'You earn {amount} more than the nearest market',
      'gross_revenue': 'Gross Revenue',
      'transport_cost': 'Transport Cost',
      'time_cost': 'Time Cost',
      'expected_loss': 'Expected Spoilage',
      'distance': 'Distance',
      'price_per_kg': 'Price',
      'travel_time': 'Travel Time',
      'why_recommended': 'Why this is recommended',
      'alternatives': 'Other Options Evaluated',
      'candidates_evaluated': '{count} markets evaluated',
      'new_search': 'Start New Search',
      'get_directions': 'Get Directions',
      'buyers': 'Buyers',
      'all': 'All',
      'verified': 'Verified',
      'pickup_available': 'Pickup Available',
      'post_your_harvest': 'Post Your Harvest',
      'crop_label': 'Crop',
      'qty_label': 'Quantity (kg)',
      'price_label': 'Expected Price (₹/kg)',
      'grade_label': 'Grade',
      'harvest_date': 'Harvest Date',
      'notes': 'Additional Notes (optional)',
      'pickup_switch': 'I can arrange delivery',
      'submit_demand': 'Post Demand',
      'demand_posted': 'Demand Posted!',
      'demand_posted_sub': 'Buyers matching your produce can now find you.',
      'post_another': 'Post Another',
      'my_demands': 'My Demands',
      'active': 'Active',
      'expired': 'Expired',
      'no_demands': 'No demands posted yet.',
      'speak_now': 'Tap the mic and speak',
      'listening': 'Listening...',
      'processing': 'Processing...',
      'type_here': 'Or type your question here...',
      'profile': 'Profile',
      'language_settings': 'Language',
      'backend_url': 'Backend URL',
      'about': 'About RythuMitra',
      'version': 'Version',
      'error_occurred': 'Something went wrong. Please try again.',
      'retry': 'Retry',
      'no_internet': 'No internet connection. Using sample data.',
      'hrs': 'hrs',
      'km': 'km',
      'kg': 'kg',
      'tons': 'tons',
      'back': 'Back',
      'next': 'Next',
      'free_pickup': 'Free Farmgate Pickup',
      'round_trip': 'Round-trip logistics',
      'view_details': 'View Details',
      'nav_home': 'Home',
      'nav_find_best': 'Find Best',
      'nav_buyers': 'Buyers',
      'nav_demand': 'Demand',
      'guide_home': 'View your dashboard and daily market updates.',
      'guide_find_best': 'Find the most profitable market based on your location and transport costs.',
      'guide_voice': 'Tap to speak! Ask for crop prices or best markets in your local language.',
      'guide_buyers': 'Connect directly with verified buyers and traders.',
      'guide_demand': 'Post your available stock and let buyers contact you.',
      'guide_notifications': 'See market updates and buyer responses.',
      'guide_profile': 'Manage your profile and preferences.',
      'history': 'History',
    },
    'te': {
      'app_name': 'రైతుమిత్ర',
      'tagline': 'అత్యధిక నికర రాబడి — కేవలం అధిక ధర కాదు',
      'select_language': 'మీ భాషను ఎంచుకోండి',
      'language_subtitle': 'మీకు అనుకూలమైన భాషను ఎంచుకోండి',
      'continue_btn': 'కొనసాగించు',
      'welcome': 'స్వాగతం',
      'farmer': 'రైతు',
      'find_best': 'అత్యుత్తమ మార్కెట్ కనుగొనండి',
      'find_best_sub': 'రవాణా & నష్టాల తర్వాత నికర లాభాన్ని లెక్కించండి',
      'buyer_network': 'క్రేతా నెట్‌వర్క్',
      'buyer_network_sub': 'వ్యాపారులు & ప్రాసెసర్లతో అనుసంధానించండి',
      'post_demand': 'డిమాండ్ పోస్ట్ చేయండి',
      'post_demand_sub': 'మీ పంటను క్రేతలకు జాబితా చేయండి',
      'voice_assistant': 'వాయిస్ అసిస్టెంట్',
      'nearby_markets': 'సమీప మార్కెట్లు',
      'mandi_prices': 'నేటి మండి ధరలు',
      'recent_searches': 'ఇటీవలి శోధనలు',
      'your_crop': 'మీ పంట',
      'select_crop': 'పంటను ఎంచుకోండి',
      'quantity': 'పరిమాణం',
      'quantity_sub': 'మీ దగ్గర ఎన్ని కిలోలు ఉన్నాయి?',
      'location': 'మీ స్థానం',
      'location_sub': 'మీ పొలం ఎక్కడ ఉంది?',
      'transport': 'రవాణా',
      'transport_sub': 'పంటను ఎలా తరలిస్తారు?',
      'own_vehicle': 'స్వంత వాహనం',
      'own_vehicle_sub': 'నా దగ్గర వాహనం ఉంది',
      'rental_vehicle': 'అద్దె వాహనం',
      'rental_vehicle_sub': 'వాహనం అద్దెకు తీసుకుంటాను',
      'no_vehicle': 'వాహనం లేదు',
      'no_vehicle_sub': 'క్రేత రవాణా అవసరం',
      'use_gps': 'GPS స్థానాన్ని ఉపయోగించు',
      'detecting': 'స్థానాన్ని గుర్తిస్తున్నాం...',
      'gps_success': 'స్థానం గుర్తించబడింది!',
      'gps_error': 'GPS పనిచేయలేదు. పట్టణాన్ని ఎంచుకోండి.',
      'search_btn': 'అత్యుత్తమ మార్కెట్ కనుగొనండి',
      'searching': 'మార్కెట్లను స్కాన్ చేస్తున్నాం...',
      'scanning_radius': '{radius} కి.మీ. వ్యాసార్థంలో స్కాన్',
      'markets_found': '{count} మార్కెట్లు కనుగొనబడ్డాయి',
      'expanding': 'శోధన పరిధి విస్తరిస్తున్నాం...',
      'calculating': 'నికర రాబడి లెక్కిస్తున్నాం...',
      'comparing': 'ధరలు, రవాణా & నష్టాలను పోల్చుతున్నాం...',
      'best_option': 'అత్యుత్తమ ఎంపిక',
      'net_realization': 'నికర రాబడి',
      'you_earn_more': 'సమీప మార్కెట్ కంటే {amount} ఎక్కువ సంపాదిస్తారు',
      'gross_revenue': 'మొత్తం అమ్మకపు విలువ',
      'transport_cost': 'రవాణా ఖర్చు',
      'time_cost': 'సమయ ఖర్చు',
      'expected_loss': 'అంచనా నష్టం',
      'distance': 'దూరం',
      'price_per_kg': 'ధర',
      'travel_time': 'ప్రయాణ సమయం',
      'why_recommended': 'ఇది ఎందుకు సిఫారసు చేయబడింది',
      'alternatives': 'ఇతర మూల్యాంకనం చేయబడిన ఎంపికలు',
      'candidates_evaluated': '{count} మార్కెట్లు మూల్యాంకనం చేయబడ్డాయి',
      'new_search': 'కొత్త శోధన',
      'get_directions': 'దిశలు పొందండి',
      'buyers': 'క్రేతలు',
      'all': 'అన్నీ',
      'verified': 'ధృవీకరించబడింది',
      'pickup_available': 'పికప్ అందుబాటులో ఉంది',
      'post_your_harvest': 'మీ పంటను పోస్ట్ చేయండి',
      'crop_label': 'పంట',
      'qty_label': 'పరిమాణం (కేజీలు)',
      'price_label': 'అంచనా ధర (₹/కేజీ)',
      'grade_label': 'గ్రేడ్',
      'harvest_date': 'పంట తేదీ',
      'notes': 'అదనపు వివరాలు (ఐచ్ఛికం)',
      'pickup_switch': 'నేను డెలివరీ ఏర్పాటు చేయగలను',
      'submit_demand': 'డిమాండ్ పోస్ట్ చేయండి',
      'demand_posted': 'డిమాండ్ పోస్ట్ చేయబడింది!',
      'demand_posted_sub': 'మీ పంటకు సరిపోయే క్రేతలు ఇప్పుడు మిమ్మల్ని కనుగొనవచ్చు.',
      'post_another': 'మరొకటి పోస్ట్ చేయండి',
      'my_demands': 'నా డిమాండ్లు',
      'active': 'చురుకుగా ఉన్నది',
      'expired': 'గడువు ముగిసింది',
      'no_demands': 'ఇంకా డిమాండ్లు పోస్ట్ చేయబడలేదు.',
      'speak_now': 'మైక్‌ను నొక్కి మాట్లాడండి',
      'listening': 'వింటున్నాం...',
      'processing': 'ప్రాసెస్ అవుతున్నది...',
      'type_here': 'లేదా ఇక్కడ టైప్ చేయండి...',
      'profile': 'ప్రొఫైల్',
      'language_settings': 'భాష',
      'backend_url': 'బ్యాక్ఎండ్ URL',
      'about': 'రైతుమిత్ర గురించి',
      'version': 'వెర్షన్',
      'error_occurred': 'ఏదో తప్పు జరిగింది. దయచేసి మళ్ళీ ప్రయత్నించండి.',
      'retry': 'మళ్ళీ ప్రయత్నించండి',
      'no_internet': 'ఇంటర్నెట్ కనెక్షన్ లేదు. నమూనా డేటా ఉపయోగిస్తున్నాం.',
      'hrs': 'గంటలు',
      'km': 'కి.మీ.',
      'kg': 'కేజీ',
      'tons': 'టన్నులు',
      'back': 'వెనక్కి',
      'next': 'తదుపరి',
      'free_pickup': 'పొలం వద్దే ఉచిత పికప్',
      'round_trip': 'రాను-పోను రవాణా ఖర్చు',
      'view_details': 'పూర్తి వివరాలు చూడండి',
      'nav_home': 'హోమ్',
      'nav_find_best': 'ఉత్తమ',
      'nav_buyers': 'క్రేతలు',
      'nav_demand': 'డిమాండ్',
      'guide_home': 'మీ డాష్‌బోర్డ్ మరియు రోజువారీ మార్కెట్ అప్‌డేట్‌లను చూడండి.',
      'guide_find_best': 'మీ స్థానం మరియు రవాణా ఖర్చుల ఆధారంగా అత్యంత లాభదాయకమైన మార్కెట్‌ను కనుగొనండి.',
      'guide_voice': 'మాట్లాడటానికి నొక్కండి! మీ స్థానిక భాషలో పంట ధరలు లేదా ఉత్తమ మార్కెట్లను అడగండి.',
      'guide_buyers': 'ధృవీకరించబడిన క్రేతలు మరియు వ్యాపారులతో నేరుగా కనెక్ట్ అవ్వండి.',
      'guide_demand': 'మీ వద్ద అందుబాటులో ఉన్న పంటను పోస్ట్ చేయండి, క్రేతలు మిమ్మల్ని సంప్రదిస్తారు.',
      'guide_notifications': 'మార్కెట్ అప్‌డేట్‌లు మరియు క్రేతల ప్రతిస్పందనలను చూడండి.',
      'guide_profile': 'మీ ప్రొఫైల్ మరియు సెట్టింగ్‌లను నిర్వహించండి.',
      'history': 'చరిత్ర',
    },
    'hi': {
      'app_name': 'रैतुमित्र',
      'tagline': 'सर्वोत्तम शुद्ध प्राप्ति — केवल उच्च मूल्य नहीं',
      'select_language': 'अपनी भाषा चुनें',
      'language_subtitle': 'वह भाषा चुनें जो आपको सुविधाजनक लगे',
      'continue_btn': 'जारी रखें',
      'welcome': 'स्वागत है',
      'farmer': 'किसान',
      'find_best': 'सर्वश्रेष्ठ विकल्प खोजें',
      'find_best_sub': 'परिवहन और जोखिम के बाद शुद्ध लाभ की गणना करें',
      'buyer_network': 'खरीदार नेटवर्क',
      'buyer_network_sub': 'व्यापारियों और प्रोसेसर से जुड़ें',
      'post_demand': 'मांग पोस्ट करें',
      'post_demand_sub': 'खरीदारों के लिए अपनी फसल सूचीबद्ध करें',
      'voice_assistant': 'वॉइस असिस्टेंट',
      'nearby_markets': 'नज़दीकी मंडियाँ',
      'mandi_prices': 'आज की मंडी कीमतें',
      'recent_searches': 'हाल की खोजें',
      'your_crop': 'आपकी फसल',
      'select_crop': 'फसल चुनें',
      'quantity': 'मात्रा',
      'quantity_sub': 'आपके पास कितने किलो हैं?',
      'location': 'आपका स्थान',
      'location_sub': 'आपका खेत कहाँ है?',
      'transport': 'परिवहन',
      'transport_sub': 'फसल कैसे ले जाएंगे?',
      'own_vehicle': 'अपना वाहन',
      'own_vehicle_sub': 'मेरे पास अपना ट्रक/वाहन है',
      'rental_vehicle': 'किराए का वाहन',
      'rental_vehicle_sub': 'मैं वाहन किराए पर लूँगा',
      'no_vehicle': 'वाहन नहीं',
      'no_vehicle_sub': 'खरीदार पिकअप या मंडी व्यवस्था चाहिए',
      'use_gps': 'GPS स्थान उपयोग करें',
      'detecting': 'स्थान ढूंढ रहे हैं...',
      'gps_success': 'स्थान मिल गया!',
      'gps_error': 'GPS काम नहीं किया। कृपया शहर चुनें।',
      'search_btn': 'सर्वश्रेष्ठ मंडी खोजें',
      'searching': 'मंडियाँ स्कैन कर रहे हैं...',
      'scanning_radius': '{radius} किमी दायरे में स्कैन',
      'markets_found': '{count} मंडियाँ मिली',
      'expanding': 'खोज दायरा बढ़ा रहे हैं...',
      'calculating': 'शुद्ध प्राप्ति की गणना कर रहे हैं...',
      'comparing': 'कीमतें, परिवहन और जोखिम तुलना कर रहे हैं...',
      'best_option': 'सर्वश्रेष्ठ विकल्प',
      'net_realization': 'शुद्ध प्राप्ति',
      'you_earn_more': 'नज़दीकी मंडी से {amount} ज़्यादा कमाई',
      'gross_revenue': 'कुल बिक्री मूल्य',
      'transport_cost': 'परिवहन खर्च',
      'time_cost': 'समय खर्च',
      'expected_loss': 'अनुमानित नुकसान',
      'distance': 'दूरी',
      'price_per_kg': 'कीमत',
      'travel_time': 'यात्रा समय',
      'why_recommended': 'यह क्यों अनुशंसित है',
      'alternatives': 'अन्य मूल्यांकित विकल्प',
      'candidates_evaluated': '{count} मंडियाँ मूल्यांकित',
      'new_search': 'नई खोज',
      'get_directions': 'दिशा पाएं',
      'buyers': 'खरीदार',
      'all': 'सभी',
      'verified': 'सत्यापित',
      'pickup_available': 'पिकअप उपलब्ध',
      'post_your_harvest': 'अपनी फसल पोस्ट करें',
      'crop_label': 'फसल',
      'qty_label': 'मात्रा (किलो)',
      'price_label': 'अपेक्षित कीमत (₹/किलो)',
      'grade_label': 'ग्रेड',
      'harvest_date': 'कटाई की तारीख',
      'notes': 'अतिरिक्त विवरण (वैकल्पिक)',
      'pickup_switch': 'मैं डिलीवरी की व्यवस्था कर सकता हूँ',
      'submit_demand': 'मांग पोस्ट करें',
      'demand_posted': 'मांग पोस्ट की गई!',
      'demand_posted_sub': 'आपकी फसल से मेल खाने वाले खरीदार अब आपको ढूंढ सकते हैं।',
      'post_another': 'एक और पोस्ट करें',
      'my_demands': 'मेरी मांगें',
      'active': 'सक्रिय',
      'expired': 'समाप्त',
      'no_demands': 'अभी तक कोई मांग पोस्ट नहीं की गई।',
      'speak_now': 'माइक दबाएं और बोलें',
      'listening': 'सुन रहे हैं...',
      'processing': 'प्रोसेस हो रहा है...',
      'type_here': 'या यहाँ टाइप करें...',
      'profile': 'प्रोफ़ाइल',
      'language_settings': 'भाषा',
      'backend_url': 'बैकएंड URL',
      'about': 'रैतुमित्र के बारे में',
      'version': 'संस्करण',
      'error_occurred': 'कुछ गलत हुआ। कृपया पुनः प्रयास करें।',
      'retry': 'पुनः प्रयास',
      'no_internet': 'इंटरनेट कनेक्शन नहीं। नमूना डेटा उपयोग कर रहे हैं।',
      'hrs': 'घंटे',
      'km': 'किमी',
      'kg': 'किलो',
      'tons': 'टन',
      'back': 'वापस',
      'next': 'अगला',
      'free_pickup': 'खेत से मुफ़्त पिकअप',
      'round_trip': 'आने-जाने का परिवहन खर्च',
      'view_details': 'पूरा विवरण देखें',
      'nav_home': 'होम',
      'nav_find_best': 'खोजें',
      'nav_buyers': 'खरीदार',
      'nav_demand': 'मांग',
      'guide_home': 'अपना डैशबोर्ड और दैनिक बाज़ार अपडेट देखें।',
      'guide_find_best': 'अपने स्थान और परिवहन लागत के आधार पर सबसे लाभदायक बाज़ार खोजें।',
      'guide_voice': 'बोलने के लिए टैप करें! अपनी स्थानीय भाषा में फसल की कीमतों या सर्वोत्तम बाज़ारों के बारे में पूछें।',
      'guide_buyers': 'सत्यापित खरीदारों और व्यापारियों से सीधे जुड़ें।',
      'guide_demand': 'अपनी उपलब्ध फसल पोस्ट करें और खरीदारों को आपसे संपर्क करने दें।',
      'guide_notifications': 'बाज़ार अपडेट और खरीदारों की प्रतिक्रियाएँ देखें।',
      'guide_profile': 'अपनी प्रोफ़ाइल और प्राथमिकताएँ प्रबंधित करें।',
      'history': 'इतिहास',
    },
  };

  static String get(String key, String langCode, {Map<String, String>? params}) {
    final lang = _data[langCode] ?? _data['en']!;
    String text = lang[key] ?? _data['en']![key] ?? key;
    params?.forEach((k, v) {
      text = text.replaceAll('{$k}', v);
    });
    return text;
  }
}
